- name: uninstall old versions of Docker
  apt:
    name:
      - docker
      - docker-engine
    state: absent

- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: true

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: add docker’s official GPG key
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  when: add_repository_key is failed

- name: add docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: install docker
  apt:
    name: "docker-ce"
    state: present
    update_cache: yes

- name:  Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true